import { Provider } from '@/components/ui/provider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="ja">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
